### ISSUE TITLE
Setup Github workflow

### ISSUE THREAD

**Issue by reblackwell3** [reblackwell3/endchess-backend#4]
The file name for a GitHub Actions workflow is typically .github/workflows/ci.yml.

Here’s how the file path would look:

bash
Copy code
.github/workflows/ci.yml
You can replace ci.yml with any other descriptive name, but it must be placed within the .github/workflows/ directory of your repository.
```
name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

    - name: Run Integration Tests
      run: npm run test:integration
```
